# IMAGEN BASE DE NODE
FROM node:18

# DIRECTORIO DE TRABAJO
WORKDIR /app

# COPIAR ARCHIVOS DE CONFIGURACIÓN
COPY package*.json ./

# INSTALAR DEPENDENCIAS
RUN npm install

# COPIAR TODO EL PROYECTO
COPY . .

# EXPONER PUERTO
EXPOSE 3000

# COMANDO PARA INICIAR LA APLICACIÓN
CMD ["node", "src/app.js"]